apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraMounts:
  # This mount is necessary for the kind cluster to access the Docker socket
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock